# Generated by Django 5.1.5 on 2025-04-21 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_driver_company_employee_company_alter_driver_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='license_number',
            new_name='licence_number',
        ),
    ]
