# Generated by Django 5.1.5 on 2025-04-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_license_number_driver_licence_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
