# Generated by Django 5.1.5 on 2025-04-27 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_alter_company_bank'),
        ('users', '0005_student_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subscribed_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.company'),
        ),
    ]
